### ISSUE TITLE
InfrastrucutureSystems v0.15.5 breaks PowerSystems v0.28.1

### ISSUE THREAD

**Issue by nickrobinson251** [NREL-SIIP/InfrastructureSystems.jl#129]
```
julia> using PowerSystems
[ Info: Precompiling PowerSystems [bcd98974-b02a-5e2f-9ee0-a103f5c450dd]
ERROR: LoadError: LoadError: UndefVarError: convert_type not defined
```

https://github.com/NREL-SIIP/InfrastructureSystems.jl/compare/v0.15.4...v0.15.5

specifically 
- InfraSys v0.15.5 deletes `convert_type`: https://github.com/NREL-SIIP/InfrastructureSystems.jl/compare/v0.15.4...v0.15.5#diff-814b9e4969b1650fb0ca1da000c6fa05L161)
- PowerSystems v0.28.1 allows InfraSys v0.5.5: https://github.com/NREL-SIIP/PowerSystems.jl/blob/0fb1f4b5e2c686b29ca828f57347899ef445e9b8/Project.toml#L27 
- ...and uses `convert_type` e.g. https://github.com/NREL-SIIP/PowerSystems.jl/blob/0fb1f4b5e2c686b29ca828f57347899ef445e9b8/src/base.jl#L1169

If that's right, here's advice on what to do https://github.com/SciML/ColPrac/blob/master/README.md#accidental-breaking-releases

---

Aside: Perhaps CI on the InfraSys repo should have run PSys tests? Here's how ChainRules.jl runs Zygote.jl tests for PR :slightly_smiling_face:
https://github.com/JuliaDiff/ChainRules.jl/blob/9663f935cecbdf490525f58d9adf6616340f7510/.github/workflows/IntegrationTestZygote.yml

---

If `IS.convert_type` was private, then PowerSys should not have been using it.
Or if `IS.convert_type` was public API, ISv0.15.5 should have been v0.16.0?

FWIW, i think the best way forward it to release a v0.15.6 that's identical to v0.15.4, then re-relase what was v0.15.5 as v0.16.0

**Comment by jd-lara** [comment]
Sorry about the mix-up. We just made the release with the fix.
