### ISSUE TITLE
`@scoped_enum` should handle words ending with `y`

### ISSUE THREAD

**Issue by kdheepak** [NREL-SIIP/InfrastructureSystems.jl#186]
I'm opening the issue to track a feature request.

**Comment by jd-lara** [comment]
should also handle words ending in s.

**Comment by daniel-thom** [comment]
Should we change this macro to work like this? I'm not sure that we can always generate the plural version. I also don't know if we can make the macro work with an optional parameter (in order to avoid breaking the interface).

```
```Julia
@scoped_enum Fruits Fruit begin
    APPLE
    ORANGE
end

value = Fruits.APPLE
```

**Comment by jd-lara** [comment]
I like the idea of this interface

**Comment by daniel-thom** [comment]
We don't export this macro anywhere, so we can make the change. The existing uses won't change.
