### ISSUE TITLE
change order of arguments filter function 

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/InfrastructureSystems.jl#300]
currently: 

```
IS.get_components(T, sys.data, filter_func)
```

correct 

```
IS.get_components(filter_func, T, sys.data)
```

**Comment by daniel-thom** [comment]
While it would be good to add this function, users don't call it directly, and so we don't technically need it. We have a correct function in PowerSystems at https://github.com/NREL-SIIP/PowerSystems.jl/blob/master/src/base.jl#L844
