### ISSUE TITLE
Passign filters_col No longer supported in PrettyTables

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/InfrastructureSystems.jl#303]
Pretty tables 2.0 no longer supports passing the kwarg `filters_col` this is impacting `IS.show_recorder_events`

**Comment by daniel-thom** [comment]
The summary of the PrettyTables reason is that the feature made it complicated to add new features. Their recommendation is to pre-filter your table with Julia functions. Seems reasonable. All we were doing was removing the walltime-timestamp column. It should be simple to add an option in `show_recorder_events` for that.
